[[main]]
  identifier = "home"
  name = "ホーム"
  url = "/"
  weight = 10
  [main.params]
    icon = "home"

[[main]]
  identifier = "archives"
  name = "アーカイブ"
  url = "/archives/"
  weight = 20
  [main.params]
    icon = "archives"

[[main]]
  identifier = "search"
  name = "検索"
  url = "/search/"
  weight = 30
  [main.params]
    icon = "search"

[[main]]
  identifier = "about"
  name = "このサイトについて"
  url = "/about/"
  weight = 40
  [main.params]
    icon = "user"

[[main]]
  identifier = "privacy-policy"
  name = "プライバシーポリシー"
  url = "/privacy-policy/"
  weight = 50
  [main.params]
    icon = "link"

[[social]]
  identifier = "x"
  name = "𝕏"
  url = "https://x.com/ryoma_dq"
  [social.params]
    icon = "brand-x"

[[social]]
  identifier = "rss"
  name = "RSS"
  url = "/index.xml"
  [social.params]
    icon = "rss"
